packages:
  - apps/*
  - packages/*
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  bcrypt: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@eleansphere/*'
