/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDelete: typeof import('./src/components/ConfirmDelete.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PhotoManager: typeof import('./src/components/PhotoManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCollapsible: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UForm: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UCheckbox: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UModal: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPagination: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    USelect: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USwitch: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.11.2_200ff2e7add60b03263e4bf11d041b63/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
